### PR TITLE
Use spanmetrics connector to generate RED metrics

### PR DESCRIPTION
**Pull request by kovrus**
# Changes

Use spanmetrics connector to generate RED metrics.

The `span2metrics` in combination with the `prometheusremotewrite` exporter will be producing:
 
- `target_info` series
- `traces_spanmetrics_calls_total` series
- `traces_spanmetrics_duration_seconds_{count/sum/bucket}` series. If we want to temporarily produce what [Tempo metrics generator](https://grafana.com/docs/tempo/latest/metrics-generator/span_metrics/#metrics) is producing we need to add `metricstransofrm` processor to rename `traces.spanmetrics.duration` to  `traces.spanmetrics.latency` and disable `--feature-gates=pkg.translator.prometheus.NormalizeName` flag to get rid of the unit prefix, then we will end up with `traces_spanmetrics_latency_{count/sum/bucket}` 

Follow up:
- Once `servicegraph` is released as connector, update the otel config to use it as connector.
- Make OTel `prometheus` exporter (the one with the text exposition format) work with `spanmetrics` connector. Currently, it all the resource attributes are copied to series attributes.

### CODE REVIEW

**Comment by gouthamve** [comment]
Can we do the Tempo metrics already in this PR? Or is it planned immediately after this?

We are building towards the Tempo metrics for July, and I am not super confident if we're updating the App O11Y app to the connector metrics and not the Tempo metrics.

**Comment by domasx2** [comment]
> Can we do the Tempo metrics already in this PR? Or is it planned immediately after this?
> 
> We are building towards the Tempo metrics for July, and I am not super confident if we're updating the App O11Y app to the connector metrics and not the Tempo metrics.

@gouthamve  my understaing is that Tempo has not yet implemented the changes we expect for June? The goal here is to have metric names & labels as we expect them to be generated by Tempo for beta launch, so we can develop against that and not against current Tempo status quo

**Comment by gouthamve** [comment]
I meant doing this in this PR as well, or in a very quick subsequent PR:

> If we want to temporarily produce what [Tempo metrics generator](https://grafana.com/docs/tempo/latest/metrics-generator/span_metrics/#metrics) is producing we need to add metricstransofrm processor to rename traces.spanmetrics.duration to traces.spanmetrics.latency and disable --feature-gates=pkg.translator.prometheus.NormalizeName flag to get rid of the unit prefix, then we will end up with traces_spanmetrics_latency_{count/sum/bucket}

I want to make sure we don't use the metric names: `traces_spanmetrics_duration_seconds_{count/sum/bucket}` in the App O11Y plugin.

**Comment by kovrus** [comment]
Pushed https://github.com/grafana/opentelemetry-demo/pull/10/commits/b8640be3d218a2ec3b44a626d03cf99208788290 . This will result in the following generated by `spanmetrics` connector metrics that are exporter by prometheus remote write exporter:
- `traces_spanmetrics_latency_{count/sum/bucket}` 
- `traces_spanmetrics_calls_total`
- `target_info`

@gouthamve @domasx2 please take a look again.

**Review by gouthamve — APPROVED** [review]
LGTM

**Comment by domasx2** [comment]
awesome, thanks!

**Pull request merged**
